name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      plan_name: iosevka

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: sudo apt install ttfautohint

    - name: Cache node modules
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          ${{github.workspace}}/package*.json
          ${{github.workspace}}/node_modules
        key: ${{runner.os}}-${{hashFiles('package*.json', 'node_modules/**')}}

    - run: npm install
      if: steps.npm-cache.outputs.cache-hit != 'true'

    - name: Cache build output
      uses: actions/cache@v2
      id: dist-cache
      with:
        path: ${{github.workspace}}/dist
        key: ${{runner.os}}-${{env.plan_name}}-${{hashFiles('build-plans.toml')}}

    - name: Build
      run: npm run build -- contents::${{env.plan_name}}
      if: steps.dist-cache.outputs.cache-hit != 'true'

    - name: Save build output
      uses: actions/upload-artifact@v2
      with:
        name: dist-output
        path: ${{github.workspace}}/dist
